name: Deploy to Beanstalk

on:
  push:
    branches: [ "main" ]
    paths:
      - 'miyog/backend/**'

env:
  AWS_REGION: ap-southeast-2
  EB_APPLICATION_NAME: MiyogBackend
  EB_ENVIRONMENT_NAME: Miyog-prod
  DEPLOY_PACKAGE_NAME: flask_app_${{ github.sha }}.zip

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Create Zip Deployment Package
      run: |
        cd miyog/backend
        zip -r ../../${{ env.DEPLOY_PACKAGE_NAME }} . -x "*.git*" "__pycache__*" "miyog.db"
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload Package to S3
      run: |
        aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://elasticbeanstalk-${{ env.AWS_REGION }}-${{ secrets.AWS_ACCOUNT_ID }}/

    - name: Create new Beanstalk Version
      run: |
        aws elasticbeanstalk create-application-version \
        --application-name ${{ env.EB_APPLICATION_NAME }} \
        --source-bundle S3Bucket="elasticbeanstalk-${{ env.AWS_REGION }}-${{ secrets.AWS_ACCOUNT_ID }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
        --version-label "ver-${{ github.sha }}" \
        --description "CommitSHA-${{ github.sha }}"

    - name: Update Beanstalk Environment
      run: |
        aws elasticbeanstalk update-environment \
        --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
        --version-label "ver-${{ github.sha }}"
# ... previous steps (Checkout, Zip, Configure AWS, Upload S3) ...

    # 1. Deploy API
    - name: Update API Environment
      run: |
        aws elasticbeanstalk update-environment \
        --environment-name Miyog-prod \
        --version-label "ver-${{ github.sha }}"

    # 2. Deploy Worker
    - name: Update Worker Environment
      run: |
        aws elasticbeanstalk update-environment \
        --environment-name MiyogWorker-env \
        --version-label "ver-${{ github.sha }}"
